import { CardData } from "components/portfolio-card/portfolio-card.model";
import { v4 as uuid } from "uuid";

export const pojectsList: CardData[] = [
  {
    tags: ["css", "react", "javaScript", "webDevelopment"],
    resources: ["angular", "ngrx", "jasmine", "typescript"],
    _id: uuid(),
    title: "The movie db clone",
    shortDescription: "Clone the movie db page",
    gitHubLink: "https://github.com/dasanchez11/the-mdb",
    liveLink: "https://glistening-melomakarona-1c7381.netlify.app/home",
    image: "https://i.ibb.co/JxbHVBv/theimdb.jpg",
    machineLearningId: "",
    date: "2022-23-11T07:00:00.000Z",
  },
  {
    tags: ["css", "react", "webDevelopment"],
    resources: ["javascript"],
    _id: uuid(),
    title: "Github Api",
    shortDescription: "Todo app and github api ",
    gitHubLink: "https://github.com/dasanchez11/github-todo",
    liveLink: "https://dancing-starburst-4465fa.netlify.app/",
    image: "https://i.ibb.co/b1jPr69/website.png",
    machineLearningId: "",
    date: "2022-15-09T07:00:00.000Z",
  },
  {
    tags: ["css", "react", "javaScript", "webDevelopment"],
    resources: ["firebase", "mongoDb", "mySql", "docker", "react", "express"],
    _id: "62f65c58c4372f7b49ad636b",
    title: "Databases Project",
    shortDescription: "Front end fetching SQL and NoSQL databases",
    gitHubLink: "https://github.com/dasanchez11/databases",
    liveLink: "https://tangerine-horse-9ae44b.netlify.app/",
    image: "https://i.ibb.co/tQbNFK1/Screen-Shot-2022-08-12-at-9-01-53-AM.jpg",
    machineLearningId: "",
    date: "2022-08-12T07:00:00.000Z",
  },
  {
    tags: ["css", "react", "javaScript", "webDevelopment"],
    resources: ["mongoDb", "react", "node", "redux", "express"],
    _id: "628af9417eb7f9be901c7bc5",
    title: "Stocks Portfolio",
    shortDescription: "Portfolio for tracking stocks and prices",
    gitHubLink: "https://github.com/dasanchez11/Stock-Portfolio",
    liveLink: "https://peppy-duckanoo-789c6c.netlify.app/",
    image: "https://i.ibb.co/9rFBDfP/Stock-portfolio.png",
    machineLearningId: "",
    date: "2022-05-22T07:00:00.000Z",
  },
  {
    tags: ["machineLearning", "python"],
    resources: ["python", "scikitLearn", "pandas"],
    _id: "613125b05730cc6a55a51bee",
    title: "Bogotá Housing",
    shortDescription:
      "Machine Learning project to determine the price of an asset",
    gitHubLink: "https://github.com/dasanchez11/Bogot-Housing",
    liveLink: "bogota_housing",
    image: "https://i.ibb.co/NxjF8NZ/Bogota-Housing.jpg",
    machineLearningId: "613125af5730cc6a55a51bec",
    date: "2021-09-02T19:27:44.382Z",
  },
  {
    tags: ["machineLearning", "python"],
    resources: ["pandas", "scikitLearn", "python"],
    _id: "611eb25eb92ce2db07971b79",
    title: "Heart Disease Prediction",
    shortDescription:
      "Machine Learning Model to predict if a pacient has heart disease",
    gitHubLink: "https://github.com/dasanchez11/Heart-Disease",
    liveLink: "heart_disease",
    image: "https://i.ibb.co/2YRyLzZ/Heart-Disease-Prediction.jpg",
    machineLearningId: "611caec4db3830b9cc76b03b",
    date: "2021-06-10T07:00:00.000Z",
  },
  {
    tags: ["machineLearning", "python"],
    resources: ["pandas", "scikitLearn", "python"],
    _id: "611eb267b92ce2db07971b7b",
    title: "Rock or Mine ",
    shortDescription:
      "Machine Learning Model to detect a Rock or a Mine using sound navigation system",
    gitHubLink: "https://github.com/dasanchez11/Sonar-KNN",
    liveLink: "sonar",
    image: "https://i.ibb.co/Cz5065S/Rock-Or-Mine.jpg",
    machineLearningId: "6121913b1129d9fb4170d5b7",
    date: "2021-06-10T07:00:00.000Z",
  },
  {
    tags: ["machineLearning", "python"],
    resources: ["python", "scikitLearn", "pandas"],
    _id: "61219fff560a30fd155abf74",
    title: "Telecom Customer Churn",
    shortDescription:
      "Machine Learning model to predict whether or not a customer will Churn",
    gitHubLink: "https://github.com/dasanchez11/Customer-Churn",
    liveLink: "telco_costumer",
    image: "https://i.ibb.co/jrBs8D7/Churn.jpg",
    machineLearningId: "61219c520fd5f3fc9866d583",
    date: "2021-06-10T07:00:00.000Z",
  },
  {
    tags: ["node", "backEnd"],
    resources: ["mongoDb", "node", "express"],
    _id: "611eb248b92ce2db07971b73",
    title: "Network API",
    shortDescription: "Node & MongoDB API",
    gitHubLink: "https://github.com/dasanchez11/memoriesAPI",
    liveLink: "",
    image: "https://i.ibb.co/YQqwKSr/Dog-Breed-API.jpg",
    machineLearningId: "",
    date: "2021-04-10T07:00:00.000Z",
  },
  {
    tags: ["css", "react", "javaScript", "webDevelopment"],
    resources: ["react", "redux", "mongoDb"],
    _id: "611eb245b92ce2db07971b71",
    title: "Network",
    shortDescription:
      "Replicate a Social Network to create,read, update,delete posts",
    gitHubLink: "https://github.com/dasanchez11/memories",
    liveLink: "https://dasanchez11.github.io/memories/",
    image: "https://i.ibb.co/K6SrSkS/Network.jpg",
    machineLearningId: "",
    date: "2021-04-10T07:00:00.000Z",
  },
  {
    tags: ["css", "react", "webDevelopment"],
    resources: ["react", "redux", "routerDom"],
    _id: "611eb24eb92ce2db07971b75",
    title: "Portafolio Edo",
    shortDescription: "Designer behance portfolio Clone",
    gitHubLink: "https://github.com/dasanchez11/portafolio-Edo",
    liveLink: "https://dasanchez11.github.io/portafolio-Edo/",
    image: "https://i.ibb.co/2nKJfsW/Portafolio-Edo.jpg",
    machineLearningId: "",
    date: "2021-01-10T07:00:00.000Z",
  },
  {
    tags: ["css", "react", "javaScript", "webDevelopment"],
    resources: ["react", "redux", "firebase", "routerDom"],
    _id: "611eb205b92ce2db07971b67",
    title: "Ecommerce",
    shortDescription: "clothes e-commerce",
    gitHubLink: "https://github.com/dasanchez11/ecommerce",
    liveLink: "http://dasanchez11.github.io/ecommerce/",
    image: "https://i.ibb.co/4YHSWVw/Ecommerce.jpg",
    machineLearningId: "",
    date: "2020-12-10T07:00:00.000Z",
  },
  {
    tags: ["css", "react", "javaScript", "webDevelopment"],
    resources: ["react", "postgressSQL", "express"],
    _id: "611eb238b92ce2db07971b6d",
    title: "Dog Breed",
    shortDescription: "Identify the breed of your Dog",
    gitHubLink: "https://github.com/dasanchez11/dog-breed-recognition",
    liveLink: "https://dasanchez11.github.io/dog-breed-recognition/",
    image: "https://i.ibb.co/x8hYQP3/DogBreed.jpg",
    machineLearningId: "",
    date: "2020-11-10T07:00:00.000Z",
  },
  {
    tags: ["flask", "backEnd"],
    resources: ["python", "flask", "tensorflow"],
    _id: "611eb243b92ce2db07971b6f",
    title: "Dog Breed API",
    shortDescription: "Flask API for dog breed recognition",
    gitHubLink: "https://github.com/dasanchez11/dog-breed-api",
    liveLink: "",
    image: "https://i.ibb.co/YQqwKSr/Dog-Breed-API.jpg",
    machineLearningId: "",
    date: "2020-11-10T07:00:00.000Z",
  },
  {
    tags: ["artificialIntelligence", "machineLearning", "All", "Python"],
    resources: ["python", "tensorflow", "pandas"],
    _id: "612403c89880e38ad1e51c29",
    title: "Dog Breed Prediction",
    shortDescription: "Predict the breed of your dog",
    gitHubLink: "https://github.com/dasanchez11/DogBreed-Model",
    liveLink: "dog_breed",
    image: "https://i.ibb.co/frV2Z2m/Dog-Breed-Prediction.jpg",
    machineLearningId: "612400c29880e38ad1e51c28",
    date: "2020-09-10T07:00:00.000Z",
  },
  {
    tags: ["node", "backEnd"],
    resources: ["node", "postgressSQL", "express"],
    _id: "611eb22db92ce2db07971b6b",
    title: "Smart Brain API",
    shortDescription: "API for face recognition APP",
    gitHubLink: "https://github.com/dasanchez11/Smart-Brain-Api",
    liveLink: "",
    image: "https://i.ibb.co/YQqwKSr/Dog-Breed-API.jpg",
    machineLearningId: "",
    date: "2020-06-20T07:00:00.000Z",
  },
  {
    tags: ["css", "react", "javaScript", "webDevelopment"],
    resources: ["react", "redux"],
    _id: "611eb219b92ce2db07971b69",
    title: "Smart Brain",
    shortDescription: "Recognize a face in an image",
    gitHubLink: "",
    liveLink: "https://smartbrainds.herokuapp.com/",
    image: "https://i.ibb.co/Jpjcmp8/Smart-Brain.jpg",
    machineLearningId: "",
    date: "2020-06-18T07:00:00.000Z",
  },
  {
    tags: ["css", "react", "webDevelopment"],
    resources: ["react"],
    _id: "611eb259b92ce2db07971b77",
    title: "RobotFriends",
    shortDescription: "Dummy api fetch for getting users",
    gitHubLink: "https://github.com/dasanchez11/Robot-Friends",
    liveLink: "https://dasanchez11.github.io/Robot-Friends/",
    image: "https://i.ibb.co/NZgxFZy/Robot-Friends.jpg",
    machineLearningId: "",
    date: "2020-04-10T07:00:00.000Z",
  },
];
