import {
  TypescriptIcon,
  AngularIcon,
  JavascriptIcon,
  MongodbIcon,
  NestjsIcon,
  ReactIcon,
  PythonIcon,
  FirebaseIcon,
  NodedotjsIcon,
  PostgressIcon,
  ScikitlearnIcon,
  PandasIcon,
  DockerIcon,
  NgrxIcon,
  ReduxIcon,
  ReactrouterIcon,
  FlaskIcon,
  MysqlIcon,
  SequalizeIcon,
  TensorflowIcon,
  JWTIcon,
  ExpressIcon,
  JasmineIcon,
  JestIcon,
} from "../assets/icons/index";

export const IconComponents = {
  typescript: TypescriptIcon,
  javascript: JavascriptIcon,
  ngrx: NgrxIcon,
  redux: ReduxIcon,
  firebase: FirebaseIcon,
  routerDom: ReactrouterIcon,
  react: ReactIcon,
  node: NodedotjsIcon,
  flask: FlaskIcon,
  postgressSQL: PostgressIcon,
  mongoDb: MongodbIcon,
  python: PythonIcon,
  scikitLearn: ScikitlearnIcon,
  pandas: PandasIcon,
  tensorflow: TensorflowIcon,
  docker: DockerIcon,
  mySql: MysqlIcon,
  sequelize: SequalizeIcon,
  jwt: JWTIcon,
  nest: NestjsIcon,
  express: ExpressIcon,
  angular: AngularIcon,
  jasmine: JasmineIcon,
  jest: JestIcon,
};
